### ISSUE TITLE
"Plugin.SimHub.SimHubConnection Cannot send to server" when ACC is restarted

### ISSUE THREAD

**Issue by Annihilannic** [pre-martin/SimHubPropertyServer#33] opened 2023-06-24 15:23 UTC
I'm using SimHubPropertyServer with the StreamDeckSimHubPlugin to display stateful buttons on my StreamDeck.

For some reason, if I have to quit and reload ACC for any reason, the stateful display no longer works.   The following log shows the working connection, followed by the failure.

If I reboot and start everything from scratch, it works again.   Just restarting SimHub doesn't resolve it.  Any suggestions, please?

```
2023-06-24 10:50:48.9499 INFO  [1  ] Plugin.SimHub.SimHubConnection Connecting to SimHub (Property Server plugin has to be installed in SimHub)...
2023-06-24 10:50:51.1828 INFO  [8  ] ub.Plugin.Actions.HotkeyAction OnWillAppear: Hotkey: l, Modifier: -A-, SimHubControl: , SimHubProperty: dcp.gd.PitLimiterOn, TitleSimHubProperty: , TitleFormat:
2023-06-24 10:50:51.1827 INFO  [16 ] ub.Plugin.Actions.HotkeyAction OnWillAppear: Hotkey: s, Modifier: ---, SimHubControl: starter, SimHubProperty: acc.physics.isEngineRunning, TitleSimHubProperty: , TitleFormat:
2023-06-24 10:50:51.1827 INFO  [6  ] ub.Plugin.Actions.HotkeyAction OnWillAppear: Hotkey: i, Modifier: --S, SimHubControl: ignition, SimHubProperty: acc.physics.ignitionOn, TitleSimHubProperty: , TitleFormat:
2023-06-24 10:50:51.1828 INFO  [6  ] Plugin.SimHub.SimHubConnection Queued subscribe request for acc.physics.ignitionOn
2023-06-24 10:50:51.1828 INFO  [6  ] Plugin.SimHub.SimHubConnection Queued subscribe request for dcp.gd.PitLimiterOn
2023-06-24 10:50:51.1828 INFO  [15 ] Plugin.SimHub.SimHubConnection Queued subscribe request for acc.physics.isEngineRunning
2023-06-24 11:04:22.4604 INFO  [11 ] Plugin.SimHub.SimHubConnection Established connection to SimHub Property Server
2023-06-24 11:04:22.4604 INFO  [11 ] Plugin.SimHub.SimHubConnection Sending subscribe for acc.physics.ignitionOn
2023-06-24 11:04:22.4604 INFO  [11 ] Plugin.SimHub.SimHubConnection Sending subscribe for dcp.gd.PitLimiterOn
2023-06-24 11:04:22.4604 INFO  [11 ] Plugin.SimHub.SimHubConnection Sending subscribe for acc.physics.isEngineRunning
2023-06-24 16:13:14.7721 INFO  [72 ] Plugin.SimHub.SimHubConnection Server closed connection
2023-06-24 16:13:14.7721 INFO  [72 ] Plugin.SimHub.SimHubConnection Connecting to SimHub (Property Server plugin has to be installed in SimHub)...
2023-06-24 22:06:04.3790 WARN  [47 ] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-24 22:06:04.4925 WARN  [46 ] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
...
```

**Comment by pre-martin** [comment] 2023-06-24 16:18
Could be a problem that Windows is not releasing TCP right after they have been closed, but keeps them open for some time. 

Could you also please post the log from the SimHub plugin: `C:\Program Files (x86)\SimHub\Logs\PropertyServer.log`. Maybe it contains an error that the listener could not be opened.

**Comment by Annihilannic** [comment] 2023-06-25 07:13
Here it is, I don't see anything to indicate a problem there:

```
2023-06-24 11:04:21,842 INFO  [1              ] rtyServer.PropertyServerPlugin [cid:(null)] Starting plugin, version 1.7.8.61393
2023-06-24 11:04:21,847 INFO  [13             ] ins.PropertyServer.Comm.Server [cid:(null)] Listening on port 18082
2023-06-24 11:04:22,457 INFO  [17             ] ins.PropertyServer.Comm.Server [cid:1     ] New connection from client 127.0.0.1:2505
2023-06-24 11:04:22,507 INFO  [17             ] ertyServer.SubscriptionManager [cid:1     ] Created new property acc.physics.ignitionOn
2023-06-24 11:04:22,511 INFO  [17             ] ertyServer.SubscriptionManager [cid:1     ] Created new property dcp.gd.PitLimiterOn
2023-06-24 11:04:22,511 INFO  [7              ] ertyServer.SubscriptionManager [cid:1     ] Created new property acc.physics.isEngineRunning
2023-06-24 11:16:30,328 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] Detected a new game
2023-06-24 11:16:30,328 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] New game is ACC
2023-06-24 12:15:47,009 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] Detected a new game
2023-06-24 12:15:47,009 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] New game is ACC
2023-06-24 15:17:11,217 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] Detected a new game
2023-06-24 15:17:11,217 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] New game is ACC
2023-06-24 16:05:12,628 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] Detected a new game
2023-06-24 16:05:12,628 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] New game is ACC
2023-06-24 16:13:14,767 INFO  [1              ] rtyServer.PropertyServerPlugin [cid:(null)] Shutting down plugin
2023-06-24 16:13:14,769 INFO  [1              ] ins.PropertyServer.Comm.Server [cid:(null)] Ending server, disconnecting 1 clients
2023-06-24 16:13:14,771 INFO  [1              ] ertyServer.SubscriptionManager [cid:(null)] Removed subscription from acc.physics.ignitionOn (0 remaining)
2023-06-24 16:13:14,771 INFO  [1              ] ertyServer.SubscriptionManager [cid:(null)] Removing property acc.physics.ignitionOn, it has no more subscriptions
2023-06-24 16:13:14,771 INFO  [1              ] ertyServer.SubscriptionManager [cid:(null)] Removed subscription from dcp.gd.PitLimiterOn (0 remaining)
2023-06-24 16:13:14,771 INFO  [1              ] ertyServer.SubscriptionManager [cid:(null)] Removing property dcp.gd.PitLimiterOn, it has no more subscriptions
2023-06-24 16:13:14,771 INFO  [1              ] ertyServer.SubscriptionManager [cid:(null)] Removed subscription from acc.physics.isEngineRunning (0 remaining)
2023-06-24 16:13:14,771 INFO  [1              ] ertyServer.SubscriptionManager [cid:(null)] Removing property acc.physics.isEngineRunning, it has no more subscriptions
2023-06-24 16:13:14,772 INFO  [6              ] ins.PropertyServer.Comm.Server [cid:1     ] Server main loop got interrupted.
2023-06-24 16:13:14,772 INFO  [6              ] ins.PropertyServer.Comm.Server [cid:1     ] Exiting Listener
2023-06-24 22:00:50,468 INFO  [1              ] rtyServer.PropertyServerPlugin [cid:(null)] Starting plugin, version 1.7.8.61393
2023-06-24 22:00:50,535 INFO  [8              ] ins.PropertyServer.Comm.Server [cid:(null)] Listening on port 18082
2023-06-24 22:01:38,549 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] Detected a new game
2023-06-24 22:01:38,549 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] New game is ACC
2023-06-25 00:15:55,250 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] Detected a new game
2023-06-25 00:15:55,251 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] New game is ACC
2023-06-25 01:27:16,181 INFO  [1              ] rtyServer.PropertyServerPlugin [cid:(null)] Shutting down plugin
2023-06-25 01:27:16,243 INFO  [1              ] ins.PropertyServer.Comm.Server [cid:(null)] Ending server, disconnecting 0 clients
2023-06-25 01:27:16,254 INFO  [31             ] ins.PropertyServer.Comm.Server [cid:(null)] Server main loop got interrupted.
2023-06-25 01:27:16,254 INFO  [31             ] ins.PropertyServer.Comm.Server [cid:(null)] Exiting Listener
```

Next time it happens I'll check for connections or listeners using port 18082 to see if there's anything unusual hanging around.

**Comment by Annihilannic** [comment] 2023-06-25 15:09
Tonight it happened the first time I loaded ACC, which is unusual:

```
$ tail -f AppData/Roaming/Elgato/StreamDeck/Plugins/net.planetrenner.simhub.sdPlugin/StreamDeckSimHub.log /c/Program\ Files\ \(x86\)/SimHub/Logs/PropertyServer.log
==> AppData/Roaming/Elgato/StreamDeck/Plugins/net.planetrenner.simhub.sdPlugin/StreamDeckSimHub.log <==
2023-06-25 00:36:02.2592 WARN  [51 ] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-25 01:01:52.1154 WARN  [142] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-25 01:01:52.2424 WARN  [143] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-25 14:29:21.8286 INFO  [1  ] Plugin.SimHub.SimHubConnection Connecting to SimHub (Property Server plugin has to be installed in SimHub)...
2023-06-25 14:29:24.0373 INFO  [8  ] ub.Plugin.Actions.HotkeyAction OnWillAppear: Hotkey: l, Modifier: -A-, SimHubControl: , SimHubProperty: dcp.gd.PitLimiterOn, TitleSimHubProperty: , TitleFormat:
2023-06-25 14:29:24.0373 INFO  [16 ] ub.Plugin.Actions.HotkeyAction OnWillAppear: Hotkey: s, Modifier: ---, SimHubControl: starter, SimHubProperty: acc.physics.isEngineRunning, TitleSimHubProperty: , TitleFormat:
2023-06-25 14:29:24.0373 INFO  [6  ] ub.Plugin.Actions.HotkeyAction OnWillAppear: Hotkey: i, Modifier: --S, SimHubControl: ignition, SimHubProperty: acc.physics.ignitionOn, TitleSimHubProperty: , TitleFormat:
2023-06-25 14:29:24.0439 INFO  [6  ] Plugin.SimHub.SimHubConnection Queued subscribe request for acc.physics.ignitionOn
2023-06-25 14:29:24.0439 INFO  [10 ] Plugin.SimHub.SimHubConnection Queued subscribe request for acc.physics.isEngineRunning
2023-06-25 14:29:24.0439 INFO  [15 ] Plugin.SimHub.SimHubConnection Queued subscribe request for dcp.gd.PitLimiterOn

==> /c/Program Files (x86)/SimHub/Logs/PropertyServer.log <==
2023-06-24 22:01:38,549 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] Detected a new game
2023-06-24 22:01:38,549 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] New game is ACC
2023-06-25 00:15:55,250 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] Detected a new game
2023-06-25 00:15:55,251 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] New game is ACC
2023-06-25 01:27:16,181 INFO  [1              ] rtyServer.PropertyServerPlugin [cid:(null)] Shutting down plugin
2023-06-25 01:27:16,243 INFO  [1              ] ins.PropertyServer.Comm.Server [cid:(null)] Ending server, disconnecting 0 clients
2023-06-25 01:27:16,254 INFO  [31             ] ins.PropertyServer.Comm.Server [cid:(null)] Server main loop got interrupted.
2023-06-25 01:27:16,254 INFO  [31             ] ins.PropertyServer.Comm.Server [cid:(null)] Exiting Listener
2023-06-26 00:06:37,688 INFO  [1              ] rtyServer.PropertyServerPlugin [cid:(null)] Starting plugin, version 1.7.8.61393
2023-06-26 00:06:37,698 INFO  [18             ] ins.PropertyServer.Comm.Server [cid:(null)] Listening on port 18082
2023-06-26 00:16:32,040 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] Detected a new game
2023-06-26 00:16:32,040 INFO  [GameLoopThread ] .PropertyServer.RawDataManager [cid:(null)] New game is ACC

==> AppData/Roaming/Elgato/StreamDeck/Plugins/net.planetrenner.simhub.sdPlugin/StreamDeckSimHub.log <==
2023-06-26 00:17:39.7632 WARN  [130] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-26 00:17:39.8848 WARN  [129] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-26 00:17:40.6203 WARN  [129] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-26 00:17:41.7366 WARN  [126] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-26 00:29:50.7955 WARN  [8  ] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-26 00:29:50.9233 WARN  [37 ] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-26 00:33:41.0886 WARN  [25 ] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-26 00:33:41.1529 WARN  [24 ] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-26 00:33:44.6258 WARN  [24 ] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-26 00:33:45.8658 WARN  [20 ] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-26 00:50:06.4881 WARN  [78 ] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-26 00:50:08.3440 WARN  [74 ] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-26 01:02:04.5435 WARN  [16 ] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
2023-06-26 01:02:04.6689 WARN  [19 ] Plugin.SimHub.SimHubConnection Cannot send to server (connected: False, tcpClient: True, tcpClient.Connected: True
```

These were the connections I could see, seems normal I think:
```
$ netstat -ant | grep 18082
  TCP    127.0.0.1:18082        0.0.0.0:0              LISTENING       InHost
  TCP    127.0.0.1:18082        127.0.0.1:18082        ESTABLISHED     InHost
```

**Comment by pre-martin** [comment] 2023-06-26 16:45
Thanks for this info. I am trying to reproduce this. There are some edge cases, which are not covered by my code. Maybe they happen more often than I was thinking. I will came back if I have further questions or a solution.

**Comment by pre-martin** [comment] 2023-06-26 18:20
I prepared a version of the Stream Deck plugin with much more detailed logging. Can you please download it from https://drive.google.com/drive/folders/1C_ztTjxbxm7UJz0WuCF6K7nmT5Uvj7Wn?usp=sharing ? Use the version from the directory `1.8.17.43597 - Debug`. Installation should be easy by just double clicking on the file.

This version will output a little bit more data into the log file `StreamDeckSimHub.log`. Maybe you can try to reproduce the problem by just switching games in SimHub back and forth (instead of starting and stopping ACC). The effect should be the same.

I would be interested in the file `StreamDeckSimHub.log` - with as much lines before and after the timestamp when the problem occurred.

Afterwards you can turn the logging back to normal by editing the file `%AppData%\Elgato\StreamDeck\Plugins\net.planetrenner.simhub.sdPlugin\appsettings.json`: Line 21 contains the value `Trace` - please change it to `Info`.

You can keep this version installed - no need to go back to 1.7.8.

**Comment by pre-martin** [comment] 2023-06-27 06:03
That's the anatomy of a bug: always there when you don't need it, but never to be found when you're looking for it.

The code contains a tiny additional modification (another timeout). With some luck, that already fixes the problem. But let's wait and see, when you had more time to test.

**Comment by Annihilannic** [comment] 2023-07-03 03:51
Well, I've done a few races since, including a 12-hour enduro, updating StreamDeck software while running the game, stopping and starting applications in various orders, etc. and not had the problem again, so I suspect that little timeout change helped!  I'll keep running the debug version and let you know if it reappears... but thanks!

**Comment by pre-martin** [comment] 2023-07-03 05:03
Thank you for the update.

**Comment by pre-martin** [comment] 2023-07-13 20:35
I hope that the problem is resolved for you, thus I am closing this ticket. If you still have problems, please feel free to open a new ticket.

**Closed by pre-martin** 2023-07-13 20:35 UTC
